spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=taskList
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/database.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
security:
  jwt:
    secret: YXNrZGpsZmhhc2praHZsYXp4aXVjeXh1aW95d29pZXJibW4sU0JDbGFpc3VkeWY=
    access: 360000000000000
    refresh: 25920000000000000

